import type { TechnicalCapability } from "@/types/portfolio";

export const technicalCapabilities: TechnicalCapability[] = [
  {
    name: "Backend module development and maintenance",
    category: "backend",
    context: "Professional backend development responsibilities.",
    experienceType: "professional",
  },
  {
    name: "Database operations",
    category: "database",
    context: "Professional experience managing database operations, validation, and updates.",
    experienceType: "professional",
  },
  {
    name: "Data validation and updates",
    category: "data",
    context: "Professional backend responsibilities.",
    experienceType: "professional",
  },
  {
    name: "Error handling",
    category: "backend",
    context: "Professional backend responsibility.",
    experienceType: "professional",
  },
  {
    name: "API integration/support",
    category: "api",
    context: "Professional experience supporting API integration.",
    experienceType: "professional",
    notes: "API development experience has not been verified and is not claimed.",
  },
  {
    name: "Manual testing",
    category: "testing",
    context: "Professional testing experience.",
    experienceType: "professional",
  },
  {
    name: "Functional testing",
    category: "testing",
    context: "Professional testing experience.",
    experienceType: "professional",
  },
  {
    name: "Regression testing",
    category: "testing",
    context: "Professional testing experience.",
    experienceType: "professional",
  },
  {
    name: "Defect identification and tracking",
    category: "testing",
    context: "Professional testing experience through defect closure.",
    experienceType: "professional",
  },
  {
    name: "Technical support and troubleshooting",
    category: "support",
    context: "Professional technical support and issue-resolution responsibilities.",
    experienceType: "professional",
  },
  {
    name: "Testing and support coordination",
    category: "support",
    context: "Professional coordination with testing and support teams.",
    experienceType: "professional",
  },
  {
    name: "PHP 8.5",
    category: "backend",
    context: "Personal hands-on use.",
    experienceType: "personal",
    notes: "Approximately 1 year 11 months of personal hands-on use across the listed personal technologies.",
  },
  {
    name: "Laravel 12",
    category: "backend",
    context: "Personal hands-on use.",
    experienceType: "personal",
    notes: "Approximately 1 year 11 months of personal hands-on use across the listed personal technologies.",
  },
  {
    name: "MySQL",
    category: "database",
    context: "Personal hands-on use.",
    experienceType: "personal",
    notes: "Approximately 1 year 11 months of personal hands-on use across the listed personal technologies.",
  },
  {
    name: "PostgreSQL",
    category: "database",
    context: "Personal hands-on use.",
    experienceType: "personal",
    notes: "Approximately 1 year 11 months of personal hands-on use across the listed personal technologies.",
  },
  {
    name: "HTML",
    category: "frontend",
    context: "Listed technical skill; professional proficiency level is not established.",
    experienceType: "training",
  },
  {
    name: "CSS",
    category: "frontend",
    context: "Listed technical skill; professional proficiency level is not established.",
    experienceType: "training",
  },
  {
    name: "Angular",
    category: "frontend",
    context: "Listed technical skill; professional proficiency level is not established.",
    experienceType: "training",
  },
  {
    name: "React",
    category: "frontend",
    context: "Listed technical skill; professional proficiency level is not established.",
    experienceType: "training",
  },
  {
    name: "Git",
    category: "tooling",
    context: "Listed technical skill; no public GitHub profile is currently verified.",
    experienceType: "training",
  },
];
